from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 151)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.first_label = QtWidgets.QLabel(self.centralwidget)
        self.first_label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.first_label.setObjectName("first_label")
        self.second_label = QtWidgets.QLabel(self.centralwidget)
        self.second_label.setGeometry(QtCore.QRect(140, 10, 71, 16))
        self.second_label.setObjectName("second_label")
        self.first_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.first_lineEdit.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.first_lineEdit.setObjectName("first_lineEdit")
        self.second_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.second_lineEdit.setGeometry(QtCore.QRect(140, 30, 113, 20))
        self.second_lineEdit.setObjectName("second_lineEdit")
        self.plus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.plus_btn.setGeometry(QtCore.QRect(20, 60, 31, 23))
        self.plus_btn.setObjectName("plus_btn")
        self.minus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.minus_btn.setGeometry(QtCore.QRect(70, 60, 31, 23))
        self.minus_btn.setObjectName("minus_btn")
        self.multipl_btn = QtWidgets.QPushButton(self.centralwidget)
        self.multipl_btn.setGeometry(QtCore.QRect(120, 60, 31, 23))
        self.multipl_btn.setObjectName("multipl_btn")
        self.division_btn = QtWidgets.QPushButton(self.centralwidget)
        self.division_btn.setGeometry(QtCore.QRect(170, 60, 31, 23))
        self.division_btn.setObjectName("division_btn")
        self.power_btn = QtWidgets.QPushButton(self.centralwidget)
        self.power_btn.setGeometry(QtCore.QRect(220, 60, 31, 23))
        self.power_btn.setObjectName("power_btn")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.result_label.setObjectName("result_label")
        self.result_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.result_lineEdit.setGeometry(QtCore.QRect(10, 110, 241, 20))
        self.result_lineEdit.setObjectName("result_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.first_label.setText(_translate("MainWindow", "Первое число"))
        self.second_label.setText(_translate("MainWindow", "Второе число"))
        self.plus_btn.setText(_translate("MainWindow", "+"))
        self.minus_btn.setText(_translate("MainWindow", "-"))
        self.multipl_btn.setText(_translate("MainWindow", "*"))
        self.division_btn.setText(_translate("MainWindow", "/"))
        self.power_btn.setText(_translate("MainWindow", "^"))
        self.result_label.setText(_translate("MainWindow", "Результат"))
